#!/usr/bin/env php
<?php
require('vendor/autoload.php');

try {
	Dotenv::load(__DIR__);
	Dotenv::required(['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']);

	$import = new RedshiftImporter\RedshiftImporter();
	$import->process($argv);
} catch (Exception $e) {
	echo get_class($e) . ': ' . $e->getMessage();
}